server:
  port: 8082

#Databse Properties
spring:
  application:
    name: PRODUCT-SERVICE
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/ms-product-service
    username: postgres
    password: 1234
    driverClassName: org.postgresql.Driver  

        
  
eureka:
  instance:
    prefer-ip-address : true
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
